name: za_payment_risk
version: 1.0.0
config-version: 2

profile: za_payment_risk

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  za_payment_risk:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  za_payment_risk:
    +schema: raw
