"""
Compliance Investigation Agent — ZA Payment Risk Pipeline.

Monitors the za.payments.alerts Kafka topic. For every HIGH or CRITICAL
alert it automatically investigates the transaction, pulls originator
history from DuckDB, explains each rule violation in plain English,
and produces a structured finding report.
"""

import json
import os
import duckdb
import ollama
from datetime import datetime, timezone
from pathlib import Path
from kafka import KafkaConsumer
from jinja2 import Template

KAFKA_BROKERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
TOPIC_ALERTS  = os.getenv("TOPIC_ALERTS", "za.payments.alerts")
DB_PATH       = os.path.expanduser("~/za-payment-risk-pipeline/data/za_payments.duckdb")
FINDINGS_DIR  = Path(__file__).parent.parent.parent.parent / "findings"
OLLAMA_MODEL  = "llama3.2"

FINDINGS_DIR.mkdir(exist_ok=True)

REPORT_TEMPLATE = Template("""
# Compliance Investigation Finding
**Report ID:** {{ report_id }}
**Generated:** {{ generated_at }}
**Status:** {{ status }}

---

## Transaction Summary
| Field | Value |
|---|---|
| Transaction ID | {{ txn.transaction_id }} |
| Bank | {{ txn.bank_code }} |
| Destination | {{ txn.beneficiary_country }} |
| Amount | R{{ "{:,.2f}".format(txn.amount_zar) }} |
| BOP Code | {{ txn.bop_category_code }} |
| Risk Score | {{ txn.risk_score }} / 100 |
| Risk Band | {{ txn.risk_band }} |
| SAR Required | {{ "YES — FILE IMMEDIATELY" if txn.requires_sar else "No" }} |

---

## Rule Violations ({{ violations|length }})
{% for v in violations %}
### {{ loop.index }}. {{ v.rule_id }} — {{ v.severity }}
**Finding:** {{ v.finding }}
**Field:** {{ v.field_ref }}

{% endfor %}

---

## Originator History
| Metric | Value |
|---|---|
| Total Transactions | {{ history.total_transactions }} |
| Total Volume (ZAR) | R{{ "{:,.2f}".format(history.total_volume) }} |
| Previous Violations | {{ history.previous_violations }} |
| ADA Used YTD | R{{ "{:,.2f}".format(history.ada_ytd) }} |
| ADA Utilisation | {{ history.ada_utilisation_pct }}% |

---

## AI Analysis
{{ ai_analysis }}

---

## Recommended Action
{{ recommended_action }}

---
*Generated by ZA Payment Risk Pipeline Compliance Investigation Agent*
""")


def get_db_connection():
    if not os.path.exists(DB_PATH):
        return None
    return duckdb.connect(DB_PATH, read_only=True)


def get_originator_history(originator_id: str) -> dict:
    conn = get_db_connection()
    if not conn:
        return {
            "total_transactions": 0,
            "total_volume": 0.0,
            "previous_violations": 0,
            "ada_ytd": 0.0,
            "ada_utilisation_pct": 0.0,
        }
    try:
        result = conn.execute("""
            SELECT
                COUNT(*)                                as total_transactions,
                COALESCE(SUM(amount_zar), 0)           as total_volume,
                COALESCE(SUM(violation_count), 0)      as previous_violations,
                COALESCE(MAX(ada_ytd_used), 0)         as ada_ytd,
                COALESCE(MAX(ada_utilisation_pct), 0)  as ada_utilisation_pct
            FROM main.stg_payments
            WHERE originator_id = ?
        """, [originator_id]).fetchone()
        conn.close()
        return {
            "total_transactions":  result[0] or 0,
            "total_volume":        float(result[1] or 0),
            "previous_violations": result[2] or 0,
            "ada_ytd":             float(result[3] or 0),
            "ada_utilisation_pct": float(result[4] or 0),
        }
    except Exception:
        conn.close()
        return {
            "total_transactions": 0,
            "total_volume": 0.0,
            "previous_violations": 0,
            "ada_ytd": 0.0,
            "ada_utilisation_pct": 0.0,
        }


def build_ai_prompt(alert: dict, history: dict) -> str:
    violations_text = "\n".join([
        f"- {v['rule_id']}: {v['finding']}"
        for v in alert.get("violations", [])
    ])
    return f"""You are a compliance analyst at a South African bank reviewing a flagged cross-border payment.

TRANSACTION DETAILS:
- Transaction ID: {alert.get('transaction_id')}
- Bank: {alert.get('bank_code')}
- Destination country: {alert.get('beneficiary_country')}
- Amount: R{alert.get('amount_zar', 0):,.2f}
- Risk score: {alert.get('risk_score')} / 100
- Risk band: {alert.get('risk_band')}

RULE VIOLATIONS:
{violations_text}

ORIGINATOR HISTORY:
- Total transactions on record: {history['total_transactions']}
- Total volume transacted: R{history['total_volume']:,.2f}
- Previous violations: {history['previous_violations']}
- ADA used year-to-date: R{history['ada_ytd']:,.2f}
- ADA utilisation: {history['ada_utilisation_pct']}%

Provide a brief compliance analysis (3-4 sentences) covering:
1. The primary risk concern with this transaction
2. Whether the originator history shows a pattern of concern
3. Your overall risk assessment

Be direct and professional. Write as a compliance analyst would in an internal report."""


def get_recommended_action(alert: dict) -> str:
    risk_band    = alert.get("risk_band", "")
    requires_sar = alert.get("requires_sar", False)
    country      = alert.get("beneficiary_country", "")

    if requires_sar:
        return (
            f"BLOCK transaction and FILE SUSPICIOUS ACTIVITY REPORT immediately. "
            f"Transaction to {country} has triggered mandatory SAR filing requirements. "
            f"Escalate to Chief Compliance Officer within 1 hour."
        )
    if risk_band == "CRITICAL":
        return (
            f"HOLD transaction pending senior compliance review. "
            f"Do not release until sign-off received from compliance manager. "
            f"Contact originator for supporting documentation."
        )
    if risk_band == "HIGH":
        return (
            f"FLAG for enhanced due diligence. Request source-of-funds documentation "
            f"from originator before processing. Review within 4 hours."
        )
    return "Monitor and log. No immediate action required."


def investigate(alert: dict) -> dict:
    print(f"\n[AGENT] Investigating {alert.get('transaction_id')} "
          f"[{alert.get('risk_band')}] score={alert.get('risk_score')}")

    originator_id = alert.get("transaction_id", "UNKNOWN")
    history       = get_originator_history(originator_id)
    print(f"[AGENT] Originator history: {history['total_transactions']} transactions, "
          f"{history['previous_violations']} previous violations")

    print(f"[AGENT] Running AI analysis via {OLLAMA_MODEL}...")
    try:
        prompt   = build_ai_prompt(alert, history)
        response = ollama.chat(
            model=OLLAMA_MODEL,
            messages=[{"role": "user", "content": prompt}],
        )
        ai_analysis = response["message"]["content"].strip()
    except Exception as e:
        ai_analysis = f"AI analysis unavailable: {e}"
    print("[AGENT] AI analysis complete.")

    report_id          = f"FIND-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}"
    recommended_action = get_recommended_action(alert)
    status             = "SAR REQUIRED" if alert.get("requires_sar") else alert.get("risk_band")

    class TxnObj:
        def __init__(self, d):
            self.__dict__.update(d)

    class HistObj:
        def __init__(self, d):
            self.__dict__.update(d)

    report_md = REPORT_TEMPLATE.render(
        report_id          = report_id,
        generated_at       = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        status             = status,
        txn                = TxnObj(alert),
        violations         = alert.get("violations", []),
        history            = HistObj(history),
        ai_analysis        = ai_analysis,
        recommended_action = recommended_action,
    )

    report_path = FINDINGS_DIR / f"{report_id}.md"
    report_path.write_text(report_md)
    print(f"[AGENT] Finding saved: {report_path}")

    finding = {
        "report_id":          report_id,
        "transaction_id":     alert.get("transaction_id"),
        "risk_band":          alert.get("risk_band"),
        "risk_score":         alert.get("risk_score"),
        "requires_sar":       alert.get("requires_sar"),
        "violations":         alert.get("violations", []),
        "originator_history": history,
        "ai_analysis":        ai_analysis,
        "recommended_action": recommended_action,
        "investigated_at":    datetime.now(timezone.utc).isoformat(),
    }
    json_path = FINDINGS_DIR / f"{report_id}.json"
    json_path.write_text(json.dumps(finding, indent=2))

    return finding


def run_agent():
    print("[AGENT] Compliance Investigation Agent starting...")
    print(f"[AGENT] Listening on topic: {TOPIC_ALERTS}")
    print(f"[AGENT] Findings will be saved to: {FINDINGS_DIR}")
    print(f"[AGENT] LLM: {OLLAMA_MODEL} via Ollama")
    print("[AGENT] Ready.\n")

    try:
        consumer = KafkaConsumer(
            TOPIC_ALERTS,
            bootstrap_servers=KAFKA_BROKERS,
            value_deserializer=lambda m: json.loads(m.decode("utf-8")),
            auto_offset_reset="earliest",
            group_id="compliance-investigation-agent",
        )

        for message in consumer:
            alert = message.value
            try:
                finding = investigate(alert)
                print(
                    f"[AGENT] Complete: {finding['report_id']} — "
                    f"{finding['recommended_action'][:80]}..."
                )
            except Exception as e:
                print(f"[AGENT] Failed for {alert.get('transaction_id')}: {e}")

    except KeyboardInterrupt:
        print("\n[AGENT] Shutting down.")


if __name__ == "__main__":
    run_agent()